# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaUm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaUm(object):
    def setupUi(self, TelaUm):
        TelaUm.setObjectName("TelaUm")
        TelaUm.resize(800, 600)
        TelaUm.setMinimumSize(QtCore.QSize(800, 600))
        TelaUm.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(TelaUm)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setMaximumSize(QtCore.QSize(800, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/telaUm.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pintura = QtWidgets.QPushButton(self.centralwidget)
        self.pintura.setGeometry(QtCore.QRect(40, 230, 171, 141))
        self.pintura.setStyleSheet("background-color: rbga(0, 0, 0, 0);")
        self.pintura.setText("")
        self.pintura.setObjectName("pintura")
        self.quadroBilhete = QtWidgets.QPushButton(self.centralwidget)
        self.quadroBilhete.setGeometry(QtCore.QRect(630, 280, 141, 141))
        self.quadroBilhete.setStyleSheet("background-color: rbga(0, 0, 0, 0);")
        self.quadroBilhete.setText("")
        self.quadroBilhete.setObjectName("quadroBilhete")
        self.escultura = QtWidgets.QPushButton(self.centralwidget)
        self.escultura.setGeometry(QtCore.QRect(290, 280, 251, 261))
        self.escultura.setStyleSheet("background-color: rbga(0, 0, 0, 0);")
        self.escultura.setText("")
        self.escultura.setObjectName("escultura")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(660, 530, 111, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/img/setaDireita.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.direita = QtWidgets.QPushButton(self.centralwidget)
        self.direita.setGeometry(QtCore.QRect(680, 540, 71, 41))
        self.direita.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.direita.setText("")
        self.direita.setObjectName("direita")
        TelaUm.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaUm)
        QtCore.QMetaObject.connectSlotsByName(TelaUm)

    def retranslateUi(self, TelaUm):
        _translate = QtCore.QCoreApplication.translate
        TelaUm.setWindowTitle(_translate("TelaUm", "MainWindow"))

